#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 -Target AppVeyor

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- Source\packages -> Source\**\packages.config
- tools -> setup.cake

deploy:
- provider: NuGet
  server: https://www.myget.org/F/erikvanbrakel/api/v2/package
  api_key:
    secure: OtvPhMbycHaLLhPWTGjvKXrJBsx/HyU+6IXFlnhOhwAnt7N5/ffoFQJVxSMJ2lnt
  skip_symbols: true
  artifact: /.*\.nupkg/
